// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Uploader.Infrastructure.Persistence;

#nullable disable

namespace Uploader.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(UploaderDbContext))]
    [Migration("20260904083733_AddPseudonymTable")]
    partial class AddPseudonymTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Uploader.Infrastructure.Persistence.Entities.ImagingStudySyncStateEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CatalogueRemoteId")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceFingerprint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("RunId");

                    b.HasIndex("Status");

                    b.ToTable("imaging_study_sync_state", (string)null);
                });

            modelBuilder.Entity("Uploader.Infrastructure.Persistence.Entities.PatientSyncStateEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CatalogueRemoteId")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceFingerprint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.HasIndex("Status");

                    b.ToTable("patient_sync_state", (string)null);
                });

            modelBuilder.Entity("Uploader.Infrastructure.Persistence.Entities.PseudonymEntity", b =>
                {
                    b.Property<string>("Kind")
                        .HasColumnType("text");

                    b.Property<string>("RealId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Pseudonym")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Kind", "RealId");

                    b.HasIndex("Kind", "Pseudonym")
                        .IsUnique();

                    b.ToTable("pseudonym", (string)null);
                });

            modelBuilder.Entity("Uploader.Infrastructure.Persistence.Entities.SampleSyncStateEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CatalogueRemoteId")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceFingerprint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("RunId");

                    b.HasIndex("Status");

                    b.ToTable("sample_sync_state", (string)null);
                });

            modelBuilder.Entity("Uploader.Infrastructure.Persistence.Entities.SequencingSyncStateEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CatalogueRemoteId")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SampleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceFingerprint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.HasIndex("SampleId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("sequencing_sync_state", (string)null);
                });

            modelBuilder.Entity("Uploader.Infrastructure.Persistence.Entities.SyncRunEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("ChangedCount")
                        .HasColumnType("integer");

                    b.Property<int>("DeletedCount")
                        .HasColumnType("integer");

                    b.Property<int>("FailedCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ScannedCount")
                        .HasColumnType("integer");

                    b.Property<int>("SkippedCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UploadedCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("sync_run", (string)null);
                });

            modelBuilder.Entity("Uploader.Infrastructure.Persistence.Entities.WsiSyncStateEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CatalogueRemoteId")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SampleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceFingerprint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.HasIndex("SampleId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("wsi_sync_state", (string)null);
                });

            modelBuilder.Entity("Uploader.Infrastructure.Persistence.Entities.ImagingStudySyncStateEntity", b =>
                {
                    b.HasOne("Uploader.Infrastructure.Persistence.Entities.PatientSyncStateEntity", null)
                        .WithMany("ImagingStudies")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Uploader.Infrastructure.Persistence.Entities.SampleSyncStateEntity", b =>
                {
                    b.HasOne("Uploader.Infrastructure.Persistence.Entities.PatientSyncStateEntity", null)
                        .WithMany("Samples")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Uploader.Infrastructure.Persistence.Entities.SequencingSyncStateEntity", b =>
                {
                    b.HasOne("Uploader.Infrastructure.Persistence.Entities.SampleSyncStateEntity", null)
                        .WithOne("Sequencing")
                        .HasForeignKey("Uploader.Infrastructure.Persistence.Entities.SequencingSyncStateEntity", "SampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Uploader.Infrastructure.Persistence.Entities.WsiSyncStateEntity", b =>
                {
                    b.HasOne("Uploader.Infrastructure.Persistence.Entities.SampleSyncStateEntity", null)
                        .WithOne("Wsi")
                        .HasForeignKey("Uploader.Infrastructure.Persistence.Entities.WsiSyncStateEntity", "SampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Uploader.Infrastructure.Persistence.Entities.PatientSyncStateEntity", b =>
                {
                    b.Navigation("ImagingStudies");

                    b.Navigation("Samples");
                });

            modelBuilder.Entity("Uploader.Infrastructure.Persistence.Entities.SampleSyncStateEntity", b =>
                {
                    b.Navigation("Sequencing");

                    b.Navigation("Wsi");
                });
#pragma warning restore 612, 618
        }
    }
}
