// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Uploader.Infrastructure.Persistence;

#nullable disable

namespace Uploader.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(UploaderDbContext))]
    partial class UploaderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Uploader.Infrastructure.Persistence.ImagingStudySyncStateEntity", b =>
                {
                    b.Property<string>("AccessionNumber")
                        .HasColumnType("text");

                    b.Property<string>("CatalogueRemoteId")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceFingerprint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AccessionNumber");

                    b.HasIndex("PatientId");

                    b.HasIndex("RunId");

                    b.HasIndex("Status");

                    b.ToTable("imaging_study_sync_state", (string)null);
                });

            modelBuilder.Entity("Uploader.Infrastructure.Persistence.PatientSyncStateEntity", b =>
                {
                    b.Property<string>("PatientId")
                        .HasColumnType("text");

                    b.Property<string>("CatalogueRemoteId")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceFingerprint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PatientId");

                    b.HasIndex("RunId");

                    b.HasIndex("Status");

                    b.ToTable("patient_sync_state", (string)null);
                });

            modelBuilder.Entity("Uploader.Infrastructure.Persistence.SampleSyncStateEntity", b =>
                {
                    b.Property<string>("SampleId")
                        .HasColumnType("text");

                    b.Property<string>("CatalogueRemoteId")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceFingerprint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SampleId");

                    b.HasIndex("PatientId");

                    b.HasIndex("RunId");

                    b.HasIndex("Status");

                    b.ToTable("sample_sync_state", (string)null);
                });

            modelBuilder.Entity("Uploader.Infrastructure.Persistence.SequencingSyncStateEntity", b =>
                {
                    b.Property<string>("PredictiveNumber")
                        .HasColumnType("text");

                    b.Property<string>("CatalogueRemoteId")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SampleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceFingerprint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PredictiveNumber");

                    b.HasIndex("RunId");

                    b.HasIndex("SampleId");

                    b.HasIndex("Status");

                    b.ToTable("sequencing_sync_state", (string)null);
                });

            modelBuilder.Entity("Uploader.Infrastructure.Persistence.SyncRunEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("ChangedCount")
                        .HasColumnType("integer");

                    b.Property<int>("DeletedCount")
                        .HasColumnType("integer");

                    b.Property<int>("FailedCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ScannedCount")
                        .HasColumnType("integer");

                    b.Property<int>("SkippedCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UploadedCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("sync_run", (string)null);
                });

            modelBuilder.Entity("Uploader.Infrastructure.Persistence.WsiSyncStateEntity", b =>
                {
                    b.Property<string>("BiopticNumber")
                        .HasColumnType("text");

                    b.Property<string>("CatalogueRemoteId")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SampleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceFingerprint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BiopticNumber");

                    b.HasIndex("RunId");

                    b.HasIndex("SampleId");

                    b.HasIndex("Status");

                    b.ToTable("wsi_sync_state", (string)null);
                });

            modelBuilder.Entity("Uploader.Infrastructure.Persistence.ImagingStudySyncStateEntity", b =>
                {
                    b.HasOne("Uploader.Infrastructure.Persistence.PatientSyncStateEntity", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Uploader.Infrastructure.Persistence.SampleSyncStateEntity", b =>
                {
                    b.HasOne("Uploader.Infrastructure.Persistence.PatientSyncStateEntity", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Uploader.Infrastructure.Persistence.SequencingSyncStateEntity", b =>
                {
                    b.HasOne("Uploader.Infrastructure.Persistence.SampleSyncStateEntity", null)
                        .WithMany()
                        .HasForeignKey("SampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Uploader.Infrastructure.Persistence.WsiSyncStateEntity", b =>
                {
                    b.HasOne("Uploader.Infrastructure.Persistence.SampleSyncStateEntity", null)
                        .WithMany()
                        .HasForeignKey("SampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
