using Riok.Mapperly.Abstractions;
using Uploader.Domain.Common;
using Uploader.Domain.Sync;
using Uploader.Infrastructure.Persistence.Entities;

namespace Uploader.Infrastructure.Persistence;

/// <summary>Maps between domain sync states and EF rows (generated by Mapperly).</summary>
[Mapper]
public static partial class SyncStateMapper
{
    public static partial PatientSyncState ToDomain(PatientSyncStateEntity entity);

    public static partial SampleSyncState ToDomain(SampleSyncStateEntity entity);

    public static partial SequencingSyncState ToDomain(SequencingSyncStateEntity entity);

    public static partial WsiSyncState ToDomain(WsiSyncStateEntity entity);

    public static partial ImagingStudySyncState ToDomain(ImagingStudySyncStateEntity entity);

    /// <summary>Copy the shared mutable columns from a domain state onto an existing EF row.</summary>
    public static partial void ApplyToEntity(ISyncState state, SyncStateEntityBase entity);

    private static PatientId ToPatientId(string value) => new(value);

    private static SampleId ToSampleId(string value) => new(value);

    private static SequencingId ToSequencingId(string value) => new(value);

    private static WsiId ToWsiId(string value) => new(value);

    private static AccessionNumber ToAccessionNumber(string value) => new(value);
}
