// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SequencingApi.Infrastructure.Persistence;

#nullable disable

namespace SequencingApi.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SequencingDbContext))]
    [Migration("20260728111815_DropRunAnalysisJobTimestamps")]
    partial class DropRunAnalysisJobTimestamps
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SequencingApi.Infrastructure.Persistence.Entities.AnalysisEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AnalysisType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PipelineName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReferenceGenome")
                        .HasColumnType("text");

                    b.Property<long>("RunSampleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RunSampleId");

                    b.ToTable("analysis", (string)null);
                });

            modelBuilder.Entity("SequencingApi.Infrastructure.Persistence.Entities.LibraryPreparationEntity", b =>
                {
                    b.Property<long>("RunSampleId")
                        .HasColumnType("bigint");

                    b.Property<int?>("InputAmount")
                        .HasColumnType("integer");

                    b.Property<int?>("IntendedInsertSize")
                        .HasColumnType("integer");

                    b.Property<int?>("IntendedReadLength")
                        .HasColumnType("integer");

                    b.Property<string>("LibraryPrepKit")
                        .HasColumnType("text");

                    b.Property<string>("PanelId")
                        .HasColumnType("text");

                    b.Property<bool?>("PcrFree")
                        .HasColumnType("boolean");

                    b.Property<string>("TargetEnrichmentKit")
                        .HasColumnType("text");

                    b.Property<bool?>("UmiPresent")
                        .HasColumnType("boolean");

                    b.HasKey("RunSampleId");

                    b.HasIndex("PanelId");

                    b.ToTable("library_preparation", (string)null);
                });

            modelBuilder.Entity("SequencingApi.Infrastructure.Persistence.Entities.PanelEntity", b =>
                {
                    b.Property<string>("PanelId")
                        .HasColumnType("text");

                    b.Property<string>("Abbreviation")
                        .HasColumnType("text");

                    b.Property<string>("Assay")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("AvailableFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("AvailableTo")
                        .HasColumnType("date");

                    b.Property<string>("CatalogueCode")
                        .HasColumnType("text");

                    b.Property<string>("Genes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetRegionsRef")
                        .HasColumnType("text");

                    b.Property<string>("Vendor")
                        .HasColumnType("text");

                    b.HasKey("PanelId");

                    b.ToTable("panel", (string)null);
                });

            modelBuilder.Entity("SequencingApi.Infrastructure.Persistence.Entities.QualityMetricsEntity", b =>
                {
                    b.Property<long>("AnalysisId")
                        .HasColumnType("bigint");

                    b.Property<double?>("MedianReadDepth")
                        .HasColumnType("double precision");

                    b.Property<int?>("ObservedReadLength")
                        .HasColumnType("integer");

                    b.HasKey("AnalysisId");

                    b.ToTable("quality_metrics", (string)null);
                });

            modelBuilder.Entity("SequencingApi.Infrastructure.Persistence.Entities.RunReadEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsIndexedRead")
                        .HasColumnType("boolean");

                    b.Property<int>("NumCycles")
                        .HasColumnType("integer");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "Position")
                        .IsUnique();

                    b.ToTable("run_read", (string)null);
                });

            modelBuilder.Entity("SequencingApi.Infrastructure.Persistence.Entities.RunSampleEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("LaneCount")
                        .HasColumnType("integer");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SampleExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SampleIndex")
                        .HasColumnType("integer");

                    b.Property<string>("SampleType")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.HasIndex("SampleExternalId", "RunId")
                        .IsUnique();

                    b.ToTable("run_sample", (string)null);
                });

            modelBuilder.Entity("SequencingApi.Infrastructure.Persistence.Entities.SampleEntity", b =>
                {
                    b.Property<string>("ExternalId")
                        .HasColumnType("text");

                    b.Property<string>("IdScheme")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PredictiveNumber")
                        .HasColumnType("text");

                    b.HasKey("ExternalId");

                    b.HasIndex("IdScheme");

                    b.HasIndex("PredictiveNumber");

                    b.ToTable("sample", (string)null);
                });

            modelBuilder.Entity("SequencingApi.Infrastructure.Persistence.Entities.SequencingFileEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AnalysisId")
                        .HasColumnType("bigint");

                    b.Property<string>("Checksum")
                        .HasColumnType("text");

                    b.Property<string>("Format")
                        .HasColumnType("text");

                    b.Property<int?>("Lane")
                        .HasColumnType("integer");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Read")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("RunSampleId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisId");

                    b.HasIndex("Role");

                    b.HasIndex("RunSampleId");

                    b.ToTable("sequencing_file", null, t =>
                        {
                            t.HasCheckConstraint("CK_sequencing_file_single_owner", "(\"RunSampleId\" IS NULL) <> (\"AnalysisId\" IS NULL)");
                        });
                });

            modelBuilder.Entity("SequencingApi.Infrastructure.Persistence.Entities.SequencingRunEntity", b =>
                {
                    b.Property<string>("RunId")
                        .HasColumnType("text");

                    b.Property<string>("Assay")
                        .HasColumnType("text");

                    b.Property<string>("Chemistry")
                        .HasColumnType("text");

                    b.Property<long?>("ClusterCountPassingFilter")
                        .HasColumnType("bigint");

                    b.Property<double?>("ClusterDensity")
                        .HasColumnType("double precision");

                    b.Property<string>("CompletionStatus")
                        .HasColumnType("text");

                    b.Property<string>("ErrorDescription")
                        .HasColumnType("text");

                    b.Property<double?>("EstimatedYield")
                        .HasColumnType("double precision");

                    b.Property<string>("ExperimentName")
                        .HasColumnType("text");

                    b.Property<string>("FlowcellId")
                        .HasColumnType("text");

                    b.Property<string>("InstrumentId")
                        .HasColumnType("text");

                    b.Property<string>("InstrumentModel")
                        .HasColumnType("text");

                    b.Property<int?>("LaneCount")
                        .HasColumnType("integer");

                    b.Property<double?>("PercentageClustersPassingFilter")
                        .HasColumnType("double precision");

                    b.Property<double?>("PercentageQ30")
                        .HasColumnType("double precision");

                    b.Property<string>("Platform")
                        .HasColumnType("text");

                    b.Property<string>("ReagentKit")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("RunDate")
                        .HasColumnType("date");

                    b.Property<int?>("RunNumber")
                        .HasColumnType("integer");

                    b.Property<string>("SourceClass")
                        .HasColumnType("text");

                    b.Property<string>("Workflow")
                        .HasColumnType("text");

                    b.HasKey("RunId");

                    b.HasIndex("RunDate");

                    b.ToTable("sequencing_run", (string)null);
                });

            modelBuilder.Entity("SequencingApi.Infrastructure.Persistence.Entities.AnalysisEntity", b =>
                {
                    b.HasOne("SequencingApi.Infrastructure.Persistence.Entities.RunSampleEntity", null)
                        .WithMany("Analyses")
                        .HasForeignKey("RunSampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SequencingApi.Infrastructure.Persistence.Entities.LibraryPreparationEntity", b =>
                {
                    b.HasOne("SequencingApi.Infrastructure.Persistence.Entities.RunSampleEntity", null)
                        .WithOne("LibraryPreparation")
                        .HasForeignKey("SequencingApi.Infrastructure.Persistence.Entities.LibraryPreparationEntity", "RunSampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SequencingApi.Infrastructure.Persistence.Entities.QualityMetricsEntity", b =>
                {
                    b.HasOne("SequencingApi.Infrastructure.Persistence.Entities.AnalysisEntity", null)
                        .WithOne("Quality")
                        .HasForeignKey("SequencingApi.Infrastructure.Persistence.Entities.QualityMetricsEntity", "AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SequencingApi.Infrastructure.Persistence.Entities.RunReadEntity", b =>
                {
                    b.HasOne("SequencingApi.Infrastructure.Persistence.Entities.SequencingRunEntity", null)
                        .WithMany("Reads")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SequencingApi.Infrastructure.Persistence.Entities.RunSampleEntity", b =>
                {
                    b.HasOne("SequencingApi.Infrastructure.Persistence.Entities.SampleEntity", null)
                        .WithMany("RunSamples")
                        .HasForeignKey("SampleExternalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SequencingApi.Infrastructure.Persistence.Entities.SequencingFileEntity", b =>
                {
                    b.HasOne("SequencingApi.Infrastructure.Persistence.Entities.AnalysisEntity", null)
                        .WithMany("Files")
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SequencingApi.Infrastructure.Persistence.Entities.RunSampleEntity", null)
                        .WithMany("Files")
                        .HasForeignKey("RunSampleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SequencingApi.Infrastructure.Persistence.Entities.AnalysisEntity", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("Quality");
                });

            modelBuilder.Entity("SequencingApi.Infrastructure.Persistence.Entities.RunSampleEntity", b =>
                {
                    b.Navigation("Analyses");

                    b.Navigation("Files");

                    b.Navigation("LibraryPreparation");
                });

            modelBuilder.Entity("SequencingApi.Infrastructure.Persistence.Entities.SampleEntity", b =>
                {
                    b.Navigation("RunSamples");
                });

            modelBuilder.Entity("SequencingApi.Infrastructure.Persistence.Entities.SequencingRunEntity", b =>
                {
                    b.Navigation("Reads");
                });
#pragma warning restore 612, 618
        }
    }
}
