using System.Text.Json.Nodes;
using Uploader.Application.Json;
using Uploader.Domain;

namespace Uploader.Application.Builders;

/// <summary>Builds an <see cref="ImagingStudy"/> (with its modality-specific series) from a raw payload.</summary>
public sealed class RadiologyBuilder
{
    public ImagingStudy BuildImagingStudy(JsonObject payload)
    {
        var accessionNumber = RawJson.RequireString(payload, "accession_number");
        return new ImagingStudy
        {
            AccessionNumber = accessionNumber,
            SourceId = RawJson.ResolveSourceId(payload, accessionNumber),
            ImagingStudyIdentifier = payload.GetString("imaging_study_identifier"),
            BelongsToPerson = payload.GetString("belongs_to_person"),
            ImagingModality = payload.GetStringList("imaging_modality"),
            BodyRegion = payload.GetStringList("body_region"),
            ImagingProcedure = payload.GetStringList("imaging_procedure"),
            ReasonForImagingProcedure = payload.GetStringList("reason_for_imaging_procedure"),
            StudyStartDate = payload.GetString("study_start_date"),
            DicomSeriesCount = payload.GetInt("dicom_series_count"),
            DicomImagesCount = payload.GetInt("dicom_images_count"),
            AffiliatedInstitution = payload.GetString("affiliated_institution"),
            CtSeries = BuildCt(payload.GetObject("ct_series")),
            MrSeries = BuildMr(payload.GetObject("mr_series")),
            UsSeries = BuildUs(payload.GetObject("us_series")),
            DxSeries = BuildDx(payload.GetObject("dx_series")),
            MgSeries = BuildMg(payload.GetObject("mg_series")),
        };
    }

    private static CtSeries? BuildCt(JsonObject? p) => p is null ? null : new CtSeries
    {
        SourceId = RawJson.ResolveSourceId(p),
        SeriesIdentifier = p.GetString("series_identifier"),
        ImagingStudyIdentifier = p.GetString("imaging_study_identifier"),
        DicomImagesCount = p.GetInt("dicom_images_count"),
        SeriesStartDate = p.GetString("series_start_date"),
        BodyRegion = p.GetString("body_region"),
        Laterality = p.GetString("laterality"),
        ImagingDevice = p.GetString("imaging_device"),
        ManufacturerOfImagingDevice = p.GetString("manufacturer_of_imaging_device"),
        SoftwareVersion = p.GetString("software_version"),
        ColorSpace = p.GetString("color_space"),
        PixelSpacing = p.GetInt("pixel_spacing"),
        ImageType = p.GetString("image_type"),
        FileFormat = p.GetString("file_format"),
        FileSize = p.GetInt("file_size"),
        ImageWidth = p.GetInt("image_width"),
        ImageHeight = p.GetInt("image_height"),
        ImageDepth = p.GetInt("image_depth"),
        NumberOfChannels = p.GetInt("number_of_channels"),
        ChannelResolution = p.GetInt("channel_resolution"),
        CompressionMethod = p.GetString("compression_method"),
        CompressionQualityLabel = p.GetString("compression_quality_label"),
        AnnotationsAvailable = p.GetBool("annotations_available"),
        TubeVoltageKvp = p.GetInt("tube_voltage_kvp"),
        XRayTubeCurrentMa = p.GetInt("x_ray_tube_current_ma"),
        ExposureTimeMs = p.GetInt("exposure_time_ms"),
        SpiralPitchFactor = p.GetDouble("spiral_pitch_factor"),
        FilterType = p.GetString("filter_type"),
        ConvolutionKernel = p.GetString("convolution_kernel"),
        FieldOfView = p.GetDouble("field_of_view"),
        SliceThickness = p.GetDouble("slice_thickness"),
        ImagingInjection = p.GetString("imaging_injection"),
        NumberOfImagePlanes = p.GetInt("number_of_image_planes"),
    };

    private static MrSeries? BuildMr(JsonObject? p) => p is null ? null : new MrSeries
    {
        SourceId = RawJson.ResolveSourceId(p),
        SeriesIdentifier = p.GetString("series_identifier"),
        ImagingStudyIdentifier = p.GetString("imaging_study_identifier"),
        DicomImagesCount = p.GetInt("dicom_images_count"),
        SeriesStartDate = p.GetString("series_start_date"),
        BodyRegion = p.GetString("body_region"),
        Laterality = p.GetString("laterality"),
        ImagingDevice = p.GetString("imaging_device"),
        ManufacturerOfImagingDevice = p.GetString("manufacturer_of_imaging_device"),
        SoftwareVersion = p.GetString("software_version"),
        ColorSpace = p.GetString("color_space"),
        PixelSpacing = p.GetInt("pixel_spacing"),
        ImageType = p.GetString("image_type"),
        FileFormat = p.GetString("file_format"),
        FileSize = p.GetInt("file_size"),
        ImageWidth = p.GetInt("image_width"),
        ImageHeight = p.GetInt("image_height"),
        ImageDepth = p.GetInt("image_depth"),
        NumberOfChannels = p.GetInt("number_of_channels"),
        ChannelResolution = p.GetInt("channel_resolution"),
        CompressionMethod = p.GetString("compression_method"),
        CompressionQualityLabel = p.GetString("compression_quality_label"),
        AnnotationsAvailable = p.GetBool("annotations_available"),
        SequenceName = p.GetString("sequence_name"),
        MagneticFieldStrength = p.GetDouble("magnetic_field_strength"),
        MrAcquisitionType = p.GetString("mr_acquisition_type"),
        RepetitionTime = p.GetDouble("repetition_time"),
        EchoTime = p.GetDouble("echo_time"),
        ImagingFrequency = p.GetDouble("imaging_frequency"),
        FlipAngle = p.GetInt("flip_angle"),
        InversionTime = p.GetInt("inversion_time"),
        ReceiveCoilName = p.GetString("receive_coil_name"),
        FieldOfView = p.GetDouble("field_of_view"),
        SliceThickness = p.GetDouble("slice_thickness"),
        ImagingInjection = p.GetString("imaging_injection"),
        NumberOfImagePlanes = p.GetInt("number_of_image_planes"),
    };

    private static UsSeries? BuildUs(JsonObject? p) => p is null ? null : new UsSeries
    {
        SourceId = RawJson.ResolveSourceId(p),
        SeriesIdentifier = p.GetString("series_identifier"),
        ImagingStudyIdentifier = p.GetString("imaging_study_identifier"),
        DicomImagesCount = p.GetInt("dicom_images_count"),
        SeriesStartDate = p.GetString("series_start_date"),
        BodyRegion = p.GetString("body_region"),
        Laterality = p.GetString("laterality"),
        ImagingDevice = p.GetString("imaging_device"),
        ManufacturerOfImagingDevice = p.GetString("manufacturer_of_imaging_device"),
        SoftwareVersion = p.GetString("software_version"),
        ColorSpace = p.GetString("color_space"),
        PixelSpacing = p.GetInt("pixel_spacing"),
        ImageType = p.GetString("image_type"),
        FileFormat = p.GetString("file_format"),
        FileSize = p.GetInt("file_size"),
        ImageWidth = p.GetInt("image_width"),
        ImageHeight = p.GetInt("image_height"),
        ImageDepth = p.GetInt("image_depth"),
        NumberOfChannels = p.GetInt("number_of_channels"),
        ChannelResolution = p.GetInt("channel_resolution"),
        CompressionMethod = p.GetString("compression_method"),
        CompressionQualityLabel = p.GetString("compression_quality_label"),
        AnnotationsAvailable = p.GetBool("annotations_available"),
        TransducerFrequencyMhz = p.GetDouble("transducer_frequency_mhz"),
        MechanicalIndex = p.GetDouble("mechanical_index"),
        ThermalIndex = p.GetDouble("thermal_index"),
    };

    private static DxSeries? BuildDx(JsonObject? p) => p is null ? null : new DxSeries
    {
        SourceId = RawJson.ResolveSourceId(p),
        SeriesIdentifier = p.GetString("series_identifier"),
        ImagingStudyIdentifier = p.GetString("imaging_study_identifier"),
        DicomImagesCount = p.GetInt("dicom_images_count"),
        SeriesStartDate = p.GetString("series_start_date"),
        BodyRegion = p.GetString("body_region"),
        Laterality = p.GetString("laterality"),
        ImagingDevice = p.GetString("imaging_device"),
        ManufacturerOfImagingDevice = p.GetString("manufacturer_of_imaging_device"),
        SoftwareVersion = p.GetString("software_version"),
        ColorSpace = p.GetString("color_space"),
        PixelSpacing = p.GetInt("pixel_spacing"),
        ImageType = p.GetString("image_type"),
        FileFormat = p.GetString("file_format"),
        FileSize = p.GetInt("file_size"),
        ImageWidth = p.GetInt("image_width"),
        ImageHeight = p.GetInt("image_height"),
        ImageDepth = p.GetInt("image_depth"),
        NumberOfChannels = p.GetInt("number_of_channels"),
        ChannelResolution = p.GetInt("channel_resolution"),
        CompressionMethod = p.GetString("compression_method"),
        CompressionQualityLabel = p.GetString("compression_quality_label"),
        AnnotationsAvailable = p.GetBool("annotations_available"),
        PatientOrientation = p.GetString("patient_orientation"),
        TubeVoltageKvp = p.GetInt("tube_voltage_kvp"),
        ExposureTimeMs = p.GetInt("exposure_time_ms"),
        ExposureMas = p.GetInt("exposure_mas"),
    };

    private static MgSeries? BuildMg(JsonObject? p) => p is null ? null : new MgSeries
    {
        SourceId = RawJson.ResolveSourceId(p),
        SeriesIdentifier = p.GetString("series_identifier"),
        ImagingStudyIdentifier = p.GetString("imaging_study_identifier"),
        DicomImagesCount = p.GetInt("dicom_images_count"),
        SeriesStartDate = p.GetString("series_start_date"),
        BodyRegion = p.GetString("body_region"),
        Laterality = p.GetString("laterality"),
        ImagingDevice = p.GetString("imaging_device"),
        ManufacturerOfImagingDevice = p.GetString("manufacturer_of_imaging_device"),
        SoftwareVersion = p.GetString("software_version"),
        ColorSpace = p.GetString("color_space"),
        PixelSpacing = p.GetInt("pixel_spacing"),
        ImageType = p.GetString("image_type"),
        FileFormat = p.GetString("file_format"),
        FileSize = p.GetInt("file_size"),
        ImageWidth = p.GetInt("image_width"),
        ImageHeight = p.GetInt("image_height"),
        ImageDepth = p.GetInt("image_depth"),
        NumberOfChannels = p.GetInt("number_of_channels"),
        ChannelResolution = p.GetInt("channel_resolution"),
        CompressionMethod = p.GetString("compression_method"),
        CompressionQualityLabel = p.GetString("compression_quality_label"),
        AnnotationsAvailable = p.GetBool("annotations_available"),
        TubeVoltageKvp = p.GetInt("tube_voltage_kvp"),
        ExposureTimeMs = p.GetInt("exposure_time_ms"),
        ExposureMas = p.GetInt("exposure_mas"),
        CompressionForceN = p.GetDouble("compression_force_n"),
    };
}
