// <auto-generated />
using System;
using BiobankApi.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BiobankApi.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BiobankDbContext))]
    [Migration("20260622124518_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BiobankApi.Infrastructure.Persistence.Entities.DiagnosticSpecimenEntity", b =>
                {
                    b.Property<string>("SampleId")
                        .HasColumnType("text");

                    b.Property<string>("Diagnosis")
                        .HasColumnType("text");

                    b.Property<string>("MaterialType")
                        .HasColumnType("text");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Retrieved")
                        .HasColumnType("text");

                    b.Property<int?>("SpecimenNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TakingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("SampleId");

                    b.HasIndex("PatientId");

                    b.ToTable("diagnostic_specimen", (string)null);
                });

            modelBuilder.Entity("BiobankApi.Infrastructure.Persistence.Entities.GenomeSampleEntity", b =>
                {
                    b.Property<string>("SampleId")
                        .HasColumnType("text");

                    b.Property<string>("AccessionNumbers")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("AvailableSamplesNo")
                        .HasColumnType("integer");

                    b.Property<string>("Biopsy")
                        .HasColumnType("text");

                    b.Property<int?>("CollectionYear")
                        .HasColumnType("integer");

                    b.Property<int?>("EventNumber")
                        .HasColumnType("integer");

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PredictiveNumber")
                        .HasColumnType("text");

                    b.Property<string>("Retrieved")
                        .HasColumnType("text");

                    b.Property<int?>("SamplesNo")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TakingDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SampleId");

                    b.HasIndex("PatientId");

                    b.ToTable("genome_sample", (string)null);
                });

            modelBuilder.Entity("BiobankApi.Infrastructure.Persistence.Entities.PatientEntity", b =>
                {
                    b.Property<string>("PatientId")
                        .HasColumnType("text");

                    b.Property<string>("AccessionNumbers")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Biobank")
                        .HasColumnType("text");

                    b.Property<int?>("BirthMonth")
                        .HasColumnType("integer");

                    b.Property<int?>("BirthYear")
                        .HasColumnType("integer");

                    b.Property<bool?>("Consent")
                        .HasColumnType("boolean");

                    b.Property<string>("Sex")
                        .HasColumnType("text");

                    b.HasKey("PatientId");

                    b.ToTable("patient", (string)null);
                });

            modelBuilder.Entity("BiobankApi.Infrastructure.Persistence.Entities.SerumSampleEntity", b =>
                {
                    b.Property<string>("SampleId")
                        .HasColumnType("text");

                    b.Property<string>("AccessionNumbers")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("AvailableSamplesNo")
                        .HasColumnType("integer");

                    b.Property<string>("Biopsy")
                        .HasColumnType("text");

                    b.Property<int?>("CollectionYear")
                        .HasColumnType("integer");

                    b.Property<string>("Diagnosis")
                        .HasColumnType("text");

                    b.Property<int?>("EventNumber")
                        .HasColumnType("integer");

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PredictiveNumber")
                        .HasColumnType("text");

                    b.Property<string>("Retrieved")
                        .HasColumnType("text");

                    b.Property<int?>("SamplesNo")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TakingDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SampleId");

                    b.HasIndex("PatientId");

                    b.ToTable("serum_sample", (string)null);
                });

            modelBuilder.Entity("BiobankApi.Infrastructure.Persistence.Entities.TissueSampleEntity", b =>
                {
                    b.Property<string>("SampleId")
                        .HasColumnType("text");

                    b.Property<string>("AccessionNumbers")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("AvailableSamplesNo")
                        .HasColumnType("integer");

                    b.Property<string>("Biopsy")
                        .HasColumnType("text");

                    b.Property<int?>("CollectionYear")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CutTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Diagnosis")
                        .HasColumnType("text");

                    b.Property<int?>("EventNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FreezeTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Morphology")
                        .HasColumnType("text");

                    b.Property<string>("PTnm")
                        .HasColumnType("text");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PredictiveNumber")
                        .HasColumnType("text");

                    b.Property<string>("Retrieved")
                        .HasColumnType("text");

                    b.Property<int?>("SamplesNo")
                        .HasColumnType("integer");

                    b.HasKey("SampleId");

                    b.HasIndex("PatientId");

                    b.ToTable("tissue_sample", (string)null);
                });

            modelBuilder.Entity("BiobankApi.Infrastructure.Persistence.Entities.DiagnosticSpecimenEntity", b =>
                {
                    b.HasOne("BiobankApi.Infrastructure.Persistence.Entities.PatientEntity", null)
                        .WithMany("DiagnosticSpecimens")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BiobankApi.Infrastructure.Persistence.Entities.GenomeSampleEntity", b =>
                {
                    b.HasOne("BiobankApi.Infrastructure.Persistence.Entities.PatientEntity", null)
                        .WithMany("GenomeSamples")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BiobankApi.Infrastructure.Persistence.Entities.SerumSampleEntity", b =>
                {
                    b.HasOne("BiobankApi.Infrastructure.Persistence.Entities.PatientEntity", null)
                        .WithMany("SerumSamples")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BiobankApi.Infrastructure.Persistence.Entities.TissueSampleEntity", b =>
                {
                    b.HasOne("BiobankApi.Infrastructure.Persistence.Entities.PatientEntity", null)
                        .WithMany("TissueSamples")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BiobankApi.Infrastructure.Persistence.Entities.PatientEntity", b =>
                {
                    b.Navigation("DiagnosticSpecimens");

                    b.Navigation("GenomeSamples");

                    b.Navigation("SerumSamples");

                    b.Navigation("TissueSamples");
                });
#pragma warning restore 612, 618
        }
    }
}
